[package]
name = "siege-render"
version = "0.1.0"
authors = ["Mike Dilger <mike@optcomp.nz>"]
description = "Siege Game Engine Rendering Component"
readme = "README.md"
license = "PROPRIETARY"

[dependencies]
error-chain = "0.11"
log = "0.4"
separator = "0.3"
serde = "1.0"
serde_derive = "1.0"
