[package]
name = "siege-render"
version = "0.2.0"
authors = ["Mike Dilger <mike@optcomp.nz>"]
description = "Siege Game Engine Rendering Component"
readme = "README.md"
license = "PROPRIETARY"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
error-chain = "0.11"
log = "0.4"
vks = "0.21"
winit = "0.10"
dacite = { git = "https://gitlab.com/mikedilger/dacite.git" }
dacite-winit = { git = "https://gitlab.com/mikedilger/dacite.git" }
siege-math = { path = "../siege-math" }
siege-mesh = { path = "../siege-mesh" }
ddsfile = { path = "../ddsfile" }
zstd = "0.4"
chrono = { version="0.4", features = [ "serde" ] }
glsl-to-spirv = "0.1"
glsl-to-spirv-macros = "0.1"
glsl-to-spirv-macros-impl = "0.1"

[target.'cfg(windows)'.dependencies]
user32-sys = "0.2"
winapi = "0.2"

[dev-dependencies]
simple_logger = "*"
