use ash::vk::types::{ComponentMapping, ComponentSwizzle, Format};
use ddsfile::{D3DFormat, DxgiFormat};

pub fn from_d3d(format: D3DFormat) -> Option<(Format, ComponentMapping)> {
    trace!("Looking to match format {:?}", format);
    match format {
        D3DFormat::A8B8G8R8 => Some((
            Format::R8g8b8a8Srgb,
            ComponentMapping {
                r: ComponentSwizzle::Identity,
                g: ComponentSwizzle::Identity,
                b: ComponentSwizzle::Identity,
                a: ComponentSwizzle::Identity,
            },
        )),
        D3DFormat::G16R16 => None,
        D3DFormat::A2B10G10R10 => None,
        D3DFormat::A1R5G5B5 => None,
        D3DFormat::R5G6B5 => None,
        D3DFormat::A8 => None,
        D3DFormat::A8R8G8B8 => Some((
            Format::R8g8b8a8Srgb,
            ComponentMapping {
                r: ComponentSwizzle::B,
                g: ComponentSwizzle::Identity,
                b: ComponentSwizzle::R,
                a: ComponentSwizzle::Identity,
            },
        )),
        D3DFormat::X8R8G8B8 => None,
        D3DFormat::X8B8G8R8 => None,
        D3DFormat::A2R10G10B10 => None,
        D3DFormat::R8G8B8 => None,
        D3DFormat::X1R5G5B5 => None,
        D3DFormat::A4R4G4B4 => None,
        D3DFormat::X4R4G4B4 => None,
        D3DFormat::A8R3G3B2 => None,
        D3DFormat::A8L8 => None,
        D3DFormat::L16 => None,
        D3DFormat::L8 => None,
        D3DFormat::A4L4 => None,
        D3DFormat::DXT1 => None,
        D3DFormat::DXT3 => None,
        D3DFormat::DXT5 => None,
        D3DFormat::R8G8_B8G8 => None,
        D3DFormat::G8R8_G8B8 => None,
        D3DFormat::A16B16G16R16 => None,
        D3DFormat::Q16W16V16U16 => None,
        D3DFormat::R16F => None,
        D3DFormat::G16R16F => None,
        D3DFormat::A16B16G16R16F => None,
        D3DFormat::R32F => None,
        D3DFormat::G32R32F => None,
        D3DFormat::A32B32G32R32F => None,
        D3DFormat::DXT2 => None,
        D3DFormat::DXT4 => None,
        D3DFormat::UYVY => None,
        D3DFormat::YUY2 => None,
        D3DFormat::CXV8U8 => None,
    }
}

pub fn from_dxgi(format: DxgiFormat) -> Option<Format> {
    trace!("Looking to match format {:?}", format);
    match format {
        DxgiFormat::Unknown => None,
        DxgiFormat::R32G32B32A32_Typeless => None,
        DxgiFormat::R32G32B32A32_Float => Some(Format::R32g32b32a32Sfloat),
        DxgiFormat::R32G32B32A32_UInt => Some(Format::R32g32b32a32Uint),
        DxgiFormat::R32G32B32A32_SInt => Some(Format::R32g32b32a32Sint),
        DxgiFormat::R32G32B32_Typeless => None,
        DxgiFormat::R32G32B32_Float => Some(Format::R32g32b32Sfloat),
        DxgiFormat::R32G32B32_UInt => Some(Format::R32g32b32Uint),
        DxgiFormat::R32G32B32_SInt => Some(Format::R32g32b32Sint),
        DxgiFormat::R16G16B16A16_Typeless => None,
        DxgiFormat::R16G16B16A16_Float => Some(Format::R16g16b16a16Sfloat),
        DxgiFormat::R16G16B16A16_UNorm => Some(Format::R16g16b16a16Unorm),
        DxgiFormat::R16G16B16A16_UInt => Some(Format::R16g16b16a16Uint),
        DxgiFormat::R16G16B16A16_SNorm => Some(Format::R16g16b16a16Snorm),
        DxgiFormat::R16G16B16A16_SInt => Some(Format::R16g16b16a16Sint),
        DxgiFormat::R32G32_Typeless => None,
        DxgiFormat::R32G32_Float => Some(Format::R32g32Sfloat),
        DxgiFormat::R32G32_UInt => Some(Format::R32g32Uint),
        DxgiFormat::R32G32_SInt => Some(Format::R32g32Sint),
        DxgiFormat::R32G8X24_Typeless => None,
        DxgiFormat::D32_Float_S8X24_UInt => Some(Format::D32SfloatS8Uint),
        DxgiFormat::R32_Float_X8X24_Typeless => None,
        DxgiFormat::X32_Typeless_G8X24_UInt => None,
        DxgiFormat::R10G10B10A2_Typeless => None,
        DxgiFormat::R10G10B10A2_UNorm => None,
        DxgiFormat::R10G10B10A2_UInt => None,
        DxgiFormat::R11G11B10_Float => None,
        DxgiFormat::R8G8B8A8_Typeless => None,
        DxgiFormat::R8G8B8A8_UNorm => Some(Format::R8g8b8a8Unorm),
        DxgiFormat::R8G8B8A8_UNorm_sRGB => Some(Format::R8g8b8a8Srgb),
        DxgiFormat::R8G8B8A8_UInt => Some(Format::R8g8b8a8Uint),
        DxgiFormat::R8G8B8A8_SNorm => Some(Format::R8g8b8a8Snorm),
        DxgiFormat::R8G8B8A8_SInt => Some(Format::R8g8b8a8Sint),
        DxgiFormat::R16G16_Typeless => None,
        DxgiFormat::R16G16_Float => Some(Format::R16g16Sfloat),
        DxgiFormat::R16G16_UNorm => Some(Format::R16g16Unorm),
        DxgiFormat::R16G16_UInt => Some(Format::R16g16Uint),
        DxgiFormat::R16G16_SNorm => Some(Format::R16g16Snorm),
        DxgiFormat::R16G16_SInt => Some(Format::R16g16Sint),
        DxgiFormat::R32_Typeless => None,
        DxgiFormat::D32_Float => Some(Format::D32Sfloat),
        DxgiFormat::R32_Float => Some(Format::R32Sfloat),
        DxgiFormat::R32_UInt => Some(Format::R32Uint),
        DxgiFormat::R32_SInt => Some(Format::R32Sint),
        DxgiFormat::R24G8_Typeless => None,
        DxgiFormat::D24_UNorm_S8_UInt => Some(Format::D24UnormS8Uint),
        DxgiFormat::R24_UNorm_X8_Typeless => None,
        DxgiFormat::X24_Typeless_G8_UInt => None,
        DxgiFormat::R8G8_Typeless => None,
        DxgiFormat::R8G8_UNorm => Some(Format::R8g8Unorm),
        DxgiFormat::R8G8_UInt => Some(Format::R8g8Uint),
        DxgiFormat::R8G8_SNorm => Some(Format::R8g8Snorm),
        DxgiFormat::R8G8_SInt => Some(Format::R8g8Sint),
        DxgiFormat::R16_Typeless => None,
        DxgiFormat::R16_Float => Some(Format::R16Sfloat),
        DxgiFormat::D16_UNorm => Some(Format::D16Unorm),
        DxgiFormat::R16_UNorm => Some(Format::R16Unorm),
        DxgiFormat::R16_UInt => Some(Format::R16Uint),
        DxgiFormat::R16_SNorm => Some(Format::R16Snorm),
        DxgiFormat::R16_SInt => Some(Format::R16Sint),
        DxgiFormat::R8_Typeless => None,
        DxgiFormat::R8_UNorm => Some(Format::R8Unorm),
        DxgiFormat::R8_UInt => Some(Format::R8Uint),
        DxgiFormat::R8_SNorm => Some(Format::R8Snorm),
        DxgiFormat::R8_SInt => Some(Format::R8Sint),
        DxgiFormat::A8_UNorm => None, // maybe dup Some(Format::R8Unorm),
        DxgiFormat::R1_UNorm => None,
        DxgiFormat::R9G9B9E5_SharedExp => None,
        DxgiFormat::R8G8_B8G8_UNorm => None,
        DxgiFormat::G8R8_G8B8_UNorm => None,
        DxgiFormat::BC1_Typeless => None,
        DxgiFormat::BC1_UNorm => Some(Format::Bc1RgbUnormBlock), // maybe RGBA variant?
        DxgiFormat::BC1_UNorm_sRGB => Some(Format::Bc1RgbSrgbBlock), // maybe RGBA variant?
        DxgiFormat::BC2_Typeless => None,
        DxgiFormat::BC2_UNorm => Some(Format::Bc2UnormBlock),
        DxgiFormat::BC2_UNorm_sRGB => Some(Format::Bc2SrgbBlock),
        DxgiFormat::BC3_Typeless => None,
        DxgiFormat::BC3_UNorm => Some(Format::Bc3UnormBlock),
        DxgiFormat::BC3_UNorm_sRGB => Some(Format::Bc3SrgbBlock),
        DxgiFormat::BC4_Typeless => None,
        DxgiFormat::BC4_UNorm => Some(Format::Bc4UnormBlock),
        DxgiFormat::BC4_SNorm => Some(Format::Bc4SnormBlock),
        DxgiFormat::BC5_Typeless => None,
        DxgiFormat::BC5_UNorm => Some(Format::Bc5UnormBlock),
        DxgiFormat::BC5_SNorm => Some(Format::Bc5SnormBlock),
        DxgiFormat::B5G6R5_UNorm => Some(Format::B5g6r5UnormPack16),
        DxgiFormat::B5G5R5A1_UNorm => Some(Format::B5g5r5a1UnormPack16),
        DxgiFormat::B8G8R8A8_UNorm => Some(Format::B8g8r8a8Unorm),
        DxgiFormat::B8G8R8X8_UNorm => None,
        DxgiFormat::R10G10B10_XR_Bias_A2_UNorm => None,
        DxgiFormat::B8G8R8A8_Typeless => None,
        DxgiFormat::B8G8R8A8_UNorm_sRGB => Some(Format::B8g8r8a8Srgb),
        DxgiFormat::B8G8R8X8_Typeless => None,
        DxgiFormat::B8G8R8X8_UNorm_sRGB => None,
        DxgiFormat::BC6H_Typeless => None,
        DxgiFormat::BC6H_UF16 => Some(Format::Bc6hUfloatBlock),
        DxgiFormat::BC6H_SF16 => Some(Format::Bc6hSfloatBlock),
        DxgiFormat::BC7_Typeless => None,
        DxgiFormat::BC7_UNorm => Some(Format::Bc7UnormBlock),
        DxgiFormat::BC7_UNorm_sRGB => Some(Format::Bc7SrgbBlock),
        DxgiFormat::AYUV => None,
        DxgiFormat::Y410 => None,
        DxgiFormat::Y416 => None,
        DxgiFormat::NV12 => None,
        DxgiFormat::P010 => None,
        DxgiFormat::P016 => None,
        DxgiFormat::Format_420_Opaque => None,
        DxgiFormat::YUY2 => None,
        DxgiFormat::Y210 => None,
        DxgiFormat::Y216 => None,
        DxgiFormat::NV11 => None,
        DxgiFormat::AI44 => None,
        DxgiFormat::IA44 => None,
        DxgiFormat::P8 => None,
        DxgiFormat::A8P8 => None,
        DxgiFormat::B4G4R4A4_UNorm => None,
        DxgiFormat::P208 => None,
        DxgiFormat::V208 => None,
        DxgiFormat::V408 => None,
        DxgiFormat::Force_UInt => None,
    }
}
